# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bookFormScreen.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BookForm(object):
    def setupUi(self, BookForm):
        BookForm.setObjectName("BookForm")
        BookForm.resize(650, 410)
        BookForm.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        BookForm.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(BookForm)
        self.centralwidget.setObjectName("centralwidget")
        self.nameLbl = QtWidgets.QLabel(self.centralwidget)
        self.nameLbl.setGeometry(QtCore.QRect(20, 25, 180, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.nameLbl.setFont(font)
        self.nameLbl.setObjectName("nameLbl")
        self.codeLbl = QtWidgets.QLabel(self.centralwidget)
        self.codeLbl.setGeometry(QtCore.QRect(20, 70, 180, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.codeLbl.setFont(font)
        self.codeLbl.setObjectName("codeLbl")
        self.nocLbl = QtWidgets.QLabel(self.centralwidget)
        self.nocLbl.setGeometry(QtCore.QRect(20, 205, 180, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.nocLbl.setFont(font)
        self.nocLbl.setObjectName("nocLbl")
        self.pubLbl = QtWidgets.QLabel(self.centralwidget)
        self.pubLbl.setGeometry(QtCore.QRect(20, 160, 180, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pubLbl.setFont(font)
        self.pubLbl.setObjectName("pubLbl")
        self.authLbl = QtWidgets.QLabel(self.centralwidget)
        self.authLbl.setGeometry(QtCore.QRect(20, 115, 180, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.authLbl.setFont(font)
        self.authLbl.setObjectName("authLbl")
        self.costLbl = QtWidgets.QLabel(self.centralwidget)
        self.costLbl.setGeometry(QtCore.QRect(20, 250, 180, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.costLbl.setFont(font)
        self.costLbl.setObjectName("costLbl")
        self.nameText = QtWidgets.QLineEdit(self.centralwidget)
        self.nameText.setGeometry(QtCore.QRect(220, 28, 400, 30))
        self.nameText.setObjectName("nameText")
        self.pubText = QtWidgets.QLineEdit(self.centralwidget)
        self.pubText.setGeometry(QtCore.QRect(220, 163, 400, 30))
        self.pubText.setObjectName("pubText")
        self.authText = QtWidgets.QLineEdit(self.centralwidget)
        self.authText.setGeometry(QtCore.QRect(220, 118, 400, 30))
        self.authText.setObjectName("authText")
        self.nocText = QtWidgets.QLineEdit(self.centralwidget)
        self.nocText.setGeometry(QtCore.QRect(220, 208, 60, 30))
        self.nocText.setObjectName("nocText")
        self.codeText = QtWidgets.QLineEdit(self.centralwidget)
        self.codeText.setGeometry(QtCore.QRect(220, 73, 60, 30))
        self.codeText.setObjectName("codeText")
        self.costText = QtWidgets.QLineEdit(self.centralwidget)
        self.costText.setGeometry(QtCore.QRect(220, 253, 100, 30))
        self.costText.setObjectName("costText")
        self.saveBtn = QtWidgets.QPushButton(self.centralwidget)
        self.saveBtn.setGeometry(QtCore.QRect(300, 310, 100, 35))
        self.saveBtn.setObjectName("saveBtn")
        self.delBtn = QtWidgets.QPushButton(self.centralwidget)
        self.delBtn.setGeometry(QtCore.QRect(410, 310, 100, 35))
        self.delBtn.setObjectName("delBtn")
        self.backBtn = QtWidgets.QPushButton(self.centralwidget)
        self.backBtn.setGeometry(QtCore.QRect(520, 310, 100, 35))
        self.backBtn.setObjectName("backBtn")
        BookForm.setCentralWidget(self.centralwidget)

        self.retranslateUi(BookForm)
        QtCore.QMetaObject.connectSlotsByName(BookForm)

    def retranslateUi(self, BookForm):
        _translate = QtCore.QCoreApplication.translate
        BookForm.setWindowTitle(_translate("BookForm", "Book Details"))
        self.nameLbl.setText(_translate("BookForm", "Name:"))
        self.codeLbl.setText(_translate("BookForm", "Code:"))
        self.nocLbl.setText(_translate("BookForm", "No. of Copies:"))
        self.pubLbl.setText(_translate("BookForm", "Publisher:"))
        self.authLbl.setText(_translate("BookForm", "Author:"))
        self.costLbl.setText(_translate("BookForm", "Cost:"))
        self.saveBtn.setText(_translate("BookForm", "Save"))
        self.delBtn.setText(_translate("BookForm", "Delete"))
        self.backBtn.setText(_translate("BookForm", "Back"))
