# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'issueScreen.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_issueScreen(object):
    def setupUi(self, issueScreen):
        issueScreen.setObjectName("issueScreen")
        issueScreen.resize(1050, 310)
        issueScreen.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        issueScreen.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(issueScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 350, 300))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.empPinLbl = QtWidgets.QLabel(self.frame)
        self.empPinLbl.setGeometry(QtCore.QRect(25, 25, 300, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.empPinLbl.setFont(font)
        self.empPinLbl.setObjectName("empPinLbl")
        self.book1Lbl = QtWidgets.QLabel(self.frame)
        self.book1Lbl.setGeometry(QtCore.QRect(25, 75, 300, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.book1Lbl.setFont(font)
        self.book1Lbl.setObjectName("book1Lbl")
        self.book2Lbl = QtWidgets.QLabel(self.frame)
        self.book2Lbl.setGeometry(QtCore.QRect(25, 125, 300, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.book2Lbl.setFont(font)
        self.book2Lbl.setObjectName("book2Lbl")
        self.book2Text = QtWidgets.QLineEdit(self.frame)
        self.book2Text.setGeometry(QtCore.QRect(220, 120, 100, 30))
        self.book2Text.setObjectName("book2Text")
        self.empPinText = QtWidgets.QLineEdit(self.frame)
        self.empPinText.setGeometry(QtCore.QRect(220, 25, 100, 30))
        self.empPinText.setObjectName("empPinText")
        self.book1Text = QtWidgets.QLineEdit(self.frame)
        self.book1Text.setGeometry(QtCore.QRect(220, 75, 100, 30))
        self.book1Text.setObjectName("book1Text")
        self.issueBookBtn = QtWidgets.QPushButton(self.frame)
        self.issueBookBtn.setGeometry(QtCore.QRect(180, 175, 140, 50))
        self.issueBookBtn.setObjectName("issueBookBtn")
        self.returnBookBtn = QtWidgets.QPushButton(self.frame)
        self.returnBookBtn.setGeometry(QtCore.QRect(25, 175, 140, 50))
        self.issueBookBtn.setObjectName("returnBookBtn")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(380, 10, 700, 281))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.bookEditText = QtWidgets.QLineEdit(self.frame_2)
        self.bookEditText.setGeometry(QtCore.QRect(300, 25, 100, 30))
        self.bookEditText.setObjectName("bookEditText")
        self.editEmpText = QtWidgets.QLineEdit(self.frame_2)
        self.editEmpText.setGeometry(QtCore.QRect(300, 75, 100, 30))
        self.editEmpText.setObjectName("editEmpText")
        self.bookEditLbl = QtWidgets.QLabel(self.frame_2)
        self.bookEditLbl.setGeometry(QtCore.QRect(25, 25, 300, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.bookEditLbl.setFont(font)
        self.bookEditLbl.setObjectName("bookEditLbl")
        self.editEmpLbl = QtWidgets.QLabel(self.frame_2)
        self.editEmpLbl.setGeometry(QtCore.QRect(25, 75, 300, 35))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.editEmpLbl.setFont(font)
        self.editEmpLbl.setObjectName("editEmpLbl")
        self.editBookDetails = QtWidgets.QPushButton(self.frame_2)
        self.editBookDetails.setGeometry(QtCore.QRect(420, 22, 215, 40))
        self.editBookDetails.setObjectName("editBookDetails")
        self.editEmpDetails = QtWidgets.QPushButton(self.frame_2)
        self.editEmpDetails.setGeometry(QtCore.QRect(420, 72, 215, 40))
        self.editEmpDetails.setObjectName("editEmpDetails")
        self.generateReportBtn = QtWidgets.QPushButton(self.frame_2)
        self.generateReportBtn.setGeometry(QtCore.QRect(160, 150, 300, 40))
        self.generateReportBtn.setObjectName("generateReportBtn")
        self.searchBooksBtn = QtWidgets.QPushButton(self.frame_2)
        self.searchBooksBtn.setGeometry(QtCore.QRect(160, 200, 300, 40))
        self.searchBooksBtn.setObjectName("searchBooksBtn")
        self.logout = QtWidgets.QPushButton(self.frame_2)
        self.logout.setGeometry(QtCore.QRect(510, 150, 90, 90))
        self.logout.setObjectName("logout")
        issueScreen.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(issueScreen)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 699, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        issueScreen.setMenuBar(self.menuBar)
        self.actionAdd_New_Employee = QtWidgets.QAction(issueScreen)
        self.actionAdd_New_Employee.setObjectName("actionAdd_New_Employee")
        self.actionAdd_New_Book = QtWidgets.QAction(issueScreen)
        self.actionAdd_New_Book.setObjectName("actionAdd_New_Book")
        self.actionAdd_New_Admin = QtWidgets.QAction(issueScreen)
        self.actionAdd_New_Admin.setObjectName("actionAdd_New_Admin")
        self.menuFile.addAction(self.actionAdd_New_Employee)
        self.menuFile.addAction(self.actionAdd_New_Book)
        self.menuFile.addAction(self.actionAdd_New_Admin)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(issueScreen)
        QtCore.QMetaObject.connectSlotsByName(issueScreen)

    def retranslateUi(self, issueScreen):
        _translate = QtCore.QCoreApplication.translate
        issueScreen.setWindowTitle(_translate("issueScreen", "LMS Workspace"))
        self.empPinLbl.setText(_translate("issueScreen", "Employee PIN:"))
        self.book1Lbl.setText(_translate("issueScreen", "Book 1 Code:"))
        self.book2Lbl.setText(_translate("issueScreen", "Book 2 Code:"))
        self.issueBookBtn.setText(_translate("issueScreen", "Issue Books"))
        self.bookEditLbl.setText(_translate("issueScreen", "Enter Book Code:"))
        self.editEmpLbl.setText(_translate("issueScreen", "Enter Employee PIN:"))
        self.editBookDetails.setText(_translate("issueScreen", "Edit Book Details"))
        self.editEmpDetails.setText(_translate("issueScreen", "Edit Employee Details"))
        self.generateReportBtn.setText(_translate("issueScreen", "Generate Reports"))
        self.searchBooksBtn.setText(_translate("issueScreen", "Search Books"))
        self.logout.setText(_translate("issueScreen", "Logout"))
        self.returnBookBtn.setText(_translate("issueScreen", "Return Books"))
        self.menuFile.setTitle(_translate("issueScreen", "File"))
        self.actionAdd_New_Employee.setText(_translate("issueScreen", "Add New Employee"))
        self.actionAdd_New_Book.setText(_translate("issueScreen", "Add New Book"))
        self.actionAdd_New_Admin.setText(_translate("issueScreen", "Add New Admin"))
